language: csharp
mono: none
dotnet: 2.0.0
script:
   -  dotnet build ESPIOT/ESPIOT.Api.Service/ESPIOT.Api.Service.csproj
   -  dotnet build FileService/FileService.Api.Service/FileService.Api.Service.csproj
   -  dotnet build Nebula/Nebula.Api.Service/Nebula.Api.Service.csproj
   -  dotnet build AdventureWorks/AdventureWorks.Api.Service/AdventureWorks.Api.Service.csproj
